name: mom6docs
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - dask
  - esmpy
  - pandas
  - netcdf4
  - matplotlib
  - nbsphinx
  - cartopy
  - pandoc
  - nbconvert
  - ipykernel
