name: mom6docs

channels:
  - conda-forge

dependencies:
  - python=3.6
  - ipykernel
  - xarray=0.16.0
  - dask
  - esmpy
  - pandas
  - netcdf4
  - matplotlib=3.2.2
  - cartopy=0.17.0
  - gcsfs
  - zarr
  - jupyterlab
  - pip
  - nc-time-axis
  - cftime=1.0.3.4
  - pydap
  - scipy
  - pip:
    - cmocean
    - git+https://github.com/xgcm/xgcm.git
    - git+https://github.com/geopython/OWSLib.git
